export const initialInstructions = [
  "character milady1 MiladyShort",
  "sleep 500",
  // "go milady1 0,8 1500",
  // "sleep 1500",
  "do milady1 Happy",
  "say milady1 800 hi there",
  "sleep 2000",
  "say milady1 2000 nice to see you again",
  "do milady1 Yes once",
  "sleep 2000",
];

export const animsToLoad = [
  "Walk",
  "Talk",
  "Boxing",
  "Idle",
  "Sad",
  "Happy",
  "Yes",
  "No",
  "Sleep",
];

export const words = [
  "the internet is a divine gift  and has immense potential",
  "im such a lucky girl",
  "the vibe is shifting... can you feel it?",
  "i hate you",
  "*bzzzz*",
  "im just a hampter",
  "everything is going to be ok",
  "i amm UNGOVERANBLE i WILL keep insertign qtips into my ear kanal",
  "im smolcore adn minipilled",
  "How to tell if u ar full of mirco plastic is micro blastic bad",
  "fresh born cyber angel  baby princess",
  "NOT a bilbically arucate angel but a cute renesainece one",
  "want some chips?",
  "*crunch crunch crunch*",
];

export const sampleUsernames = [
  "DirtyDan42",
  "NaughtyNancy88",
  "RandyRandy69",
  "SteamySteve420",
  "WickedWendy7",
  "HotForHarry",
  "RandyRoger33",
  "LustfulLisa",
  "KinkyKelly99",
  "RandyRyan",
  "SaucySusan666",
  "MischievousMike",
  "OccultOcelot",
  "JocularJackal",
  "CattyCurmudgeon",
  "IrateIbex",
  "SatiricalSalamander",
  "AbyssalAnteater",
  "WhiskeyWisecrack",
  "KitschKangaroo",
  "SnappySquid",
  "EnigmaticEchidna",
  "WittyWombat",
  "PeevishPenguin",
  "AcerbicArmadillo",
  "ObnoxiousOtter",
  "CrypticCuckoo",
  "SarcasticSquidward",
];

export const SampleMeanYoutubeComments = [
  "Not impressed 😒",
  "Boring 😴",
  "Is this it? 🤔",
  "👎",
  "Nothing new here 🔄",
  "Meh 😑",
  "Yawn... 😪",
  "Too basic 🙄",
  "Who cares? 🤷",
  "🙈 cringe",
  "Try harder 😖",
  "Do something interesting 🤷‍♀️",
  "Same old, same old 💤",
  "Seen it before 👀",
  "You can do better 🧐",
  "Not worth my time ⏰",
  "Could use more creativity 🎨",
  "🤡 content",
  "Please, stop 🛑",
  "How original...not 🙃",
  "Forgettable 💤",
  "No effort content 🤷‍♂️",
  "Why is this on my FYP? 🤦‍♀️",
  "Hard pass 👋",
  "I'm not inspired 🚮",
  "Unimpressive 💔",
  "Where's the quality? 💩",
  "Sorry, but no 🙅‍♀️",
  "Next please ➡️",
  "This ain't it, chief 🚫",
  "Get a new hobby 🎣",
  "Can't believe I watched this 🗑️",
  "Waste of time ⌛",
  "Change up your routine 🔄",
  "I've seen better 🤡",
  "0/10 effort 🙅‍♂️",
  "Try again. Fail again. Fail better. 🔄",
  "This ain't entertaining 🎭",
];
