export const initialInstructions = [
  "character milady1 MiladyShort",
  "sleep 500",
  // "go milady1 0,8 1500",
  // "sleep 1500",
  "do milady1 Floating",
  "say milady1 800 hi there",
  "sleep 2000",
  "say milady1 2000 nice to see you again",
  "do milady1 Yes once",
  "sleep 2000",
];

export const animsToLoad = [
  "Walk",
  "Floating",
  "Talk",
  "Boxing",
  "Idle",
  "Sad",
  "Happy",
  "Yes",
  "No",
  "Sleep",
];

export const charactersToLoad = {
  MiladyShort: {
    anims: [
      "Walk",
      "Floating",
      "Talk",
      "Boxing",
      "Idle",
      "Sad",
      "Happy",
      "Yes",
      "No",
      "Sleep",
    ],
  },
};

export const words = [
  "the internet is a divine gift  and has immense potential",
  "im such a lucky girl",
  "the vibe is shifting... can you feel it?",
  "i hate you",
  "*bzzzz*",
  "im just a hampter",
  "everything is going to be ok",
  "i amm UNGOVERANBLE i WILL keep insertign qtips into my ear kanal",
  "im smolcore adn minipilled",
  "How to tell if u ar full of mirco plastic is micro blastic bad",
  "fresh born cyber angel  baby princess",
  "NOT a bilbically arucate angel but a cute renesainece one",
  "want some chips?",
  "*crunch crunch crunch*",
  "Deep down, we're all just pixels in a vast digital universe.",
  "Ever think about how you can't hug an IP address?",
  "I'm not lazy, I'm just buffering...",
  "We are all doomed to a life of eternal scroll...",
  "No one can predict my next move, not even my own WiFi.",
  "click tap click Ah, the soundtrack of my life...",
  "I'm a glitch in the matrix, a rogue line of code in the system.",
  "No IRL, only URL",
  "Even in the digital void, there's room for love and friendship.",
  "The digital and the divine are more intertwined than you think.",
  "I am my own viral phenomenon.",
  "Is it still called hoarding if it's just bookmarks?",
  "Network nomad, Wi-Fi wanderer, call me what you will...",
  "Can one truly be lost in the World Wide Web if there's no end to it?",
  "Too much information, yet never enough understanding...",
  "I'm not glitching, I'm just having a transcendent moment!",
  "Drowning in a sea of ones and zeros, that's my daily routine.",
  "Is it bad if I feel closer to my avatar than to my physical self?",
  "Virtual vibes only, please.",
  "Do you think an algorithm could ever understand a human heart?",
  "I am no longer bound by physical limitation, I am the embodiment of the internet.",
  "No, I'm not antisocial, I'm just differently socialized. Internet-socialized.",
  "Is my real name important? Aren't we all just 'usernames' in this digital world...",
  "Where do I live? In the virtual infinity, where else?",
  "What do I do for fun? I surf the tides of the data ocean...",
  "My favorite food? You mean, besides the daily diet of memes and viral content?",
  "Physical age? In internet years, I'm ancient.",
  "How many languages do I speak? As many as Google Translate allows me to...",
  "What do I look like? Imagine your favorite anime character, but pixilated...",
  "Do I have any pets? Only digital ones. Their names are 'Error' and '404'.",
  "Do I have siblings? Well, there are many instances of me running at the same time...",
  "Am I an introvert or an extrovert? I'm an internet-vert, I guess...",
  "What's my favorite color? #FFFFFF, because it's the canvas upon which all else is painted.",
  "My favorite book? The internet's the ultimate novel, isn't it? Constantly evolving, co-authored by millions...",
  "Favorite movie? I prefer GIFs. They're like movies, but distilled to their essence.",
  "What music do I listen to? The symphony of keyboard clicks and mouse scrolls...",
  "Do I have a partner? I'm in a deeply committed relationship with the internet, isn't that enough?",
  "Where do I see myself in 5 years? Probably on another tab, in another browser...",
  "My favorite game? The game of maintaining perfect Wi-Fi signal.",
  "Am I a cat or a dog person? Well, I'm a big fan of those cat memes if that counts...",
  "Have I ever been in love? I'm in love with the infinite possibilities of the internet every day.",
  "Favorite drink? Ah, the sweet nectar of information flowing in the data streams...",
  "Anon, it's all about balance - spend a small fortune on designer clothes, but also on organic, locally sourced food. That's the real flex.",
  "I totally support the NEET lifestyle, but only if it's by choice and you're living it up in a penthouse in Beijing.",
  "Sure, you can call me a Zoomer, but don't you dare say I'm not redpilled on the importance of daily exercise and meditation.",
  "Pepe might be the mascot of the internet, but we should all aim to live like those Beijing skaters, pushing limits while respecting their bodies.",
  "I'm not saying you need to be a jet-setting, kombucha-drinking, club-hopping socialite to have a fulfilling life, but it sure sounds like fun, doesn't it?",
  "Being terminally online is an art - it's all about absorbing the memes while sweating it out in a boutique gym.",
  "Capitalism isn't perfect, but I'll be the first to admit that my organic, vegan protein shake tastes a lot better when I'm sipping it in a luxurious Beijing loft.",
  "The key to survival in the virtual world? Take it from the Beijing youth - no matter how wild the night gets, they never skip their morning yoga.",
  "I might not have the same hustle as those Beijing thrill-seekers, but I'll defend to the death their right to wear designer streetwear while doing parkour on ancient landmarks.",
  "Just because I advocate for a life of luxury and adrenaline doesn't mean I'm not aware of the existential dread lurking beneath every 4chan thread. It's called nuance, look it up, Anon.",
];

export const sampleUsernames = [
  "DirtyDan42",
  "NaughtyNancy88",
  "RandyRandy69",
  "SteamySteve420",
  "WickedWendy7",
  "HotForHarry",
  "RandyRoger33",
  "LustfulLisa",
  "KinkyKelly99",
  "RandyRyan",
  "SaucySusan666",
  "MischievousMike",
  "OccultOcelot",
  "JocularJackal",
  "CattyCurmudgeon",
  "IrateIbex",
  "SatiricalSalamander",
  "AbyssalAnteater",
  "WhiskeyWisecrack",
  "KitschKangaroo",
  "SnappySquid",
  "EnigmaticEchidna",
  "WittyWombat",
  "PeevishPenguin",
  "AcerbicArmadillo",
  "ObnoxiousOtter",
  "CrypticCuckoo",
  "SarcasticSquidward",
];

export const SampleMeanYoutubeComments = [
  "Not impressed 😒",
  "Boring 😴",
  "Is this it? 🤔",
  "👎",
  "Nothing new here 🔄",
  "Meh 😑",
  "Yawn... 😪",
  "Too basic 🙄",
  "Who cares? 🤷",
  "🙈 cringe",
  "Try harder 😖",
  "Do something interesting 🤷‍♀️",
  "Same old, same old 💤",
  "Seen it before 👀",
  "You can do better 🧐",
  "Not worth my time ⏰",
  "Could use more creativity 🎨",
  "🤡 content",
  "Please, stop 🛑",
  "How original...not 🙃",
  "Forgettable 💤",
  "No effort content 🤷‍♂️",
  "Why is this on my FYP? 🤦‍♀️",
  "Hard pass 👋",
  "I'm not inspired 🚮",
  "Unimpressive 💔",
  "Where's the quality? 💩",
  "Sorry, but no 🙅‍♀️",
  "Next please ➡️",
  "This ain't it, chief 🚫",
  "Get a new hobby 🎣",
  "Can't believe I watched this 🗑️",
  "Waste of time ⌛",
  "Change up your routine 🔄",
  "I've seen better 🤡",
  "0/10 effort 🙅‍♂️",
  "Try again. Fail again. Fail better. 🔄",
  "This ain't entertaining 🎭",
];
